name: Building and Publishing ng-ui2qp
env:
  TARGET: lzy-load
on:
  push:
    branches:
      - master
    paths:
      - 'projects/lzy-load/**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: npm install
        run: |
          npm i
      - name: Building Package in production
        run: |
          npm run ${{ env.TARGET }}:build:all
      - name: Check version changes
        uses: EndBug/version-check@v1 # More info about the arguments on the action page
        id: check
        with:
          diff-search: true
          file-name: projects/${{ env.TARGET }}/package.json
      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
      - name: Publish the package to NPM
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        working-directory: dist/${{ env.TARGET }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
